# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b9c4ff06141c378b91951a25d3e79381"
name = "Velore Review App"
application_url = "https://velore-review.vercel.app"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://velore-review.vercel.app/auth/callback",
  "https://velore-review.vercel.app/auth/shopify/callback",
  "https://velore-review.vercel.app/api/auth"
]
