// Auto-generated seed reviews — baked into the app so reviews show with zero external DB.
// Regenerate from a CSV anytime; edit freely.
export const SEED_REVIEWS = [
  {
    "id": "seed-001",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "titan-scent-diffuser",
    "product_id": null,
    "author_name": "Rahul Pillai",
    "author_initials": "RP",
    "author_location": "Pune, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 4,
    "title": "Good value",
    "content": "Really good diffuser and the scent is lovely. Knocked one star only because I wish the tank was a little bigger.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-24T10:00:00Z"
  },
  {
    "id": "seed-002",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "bolt-scent-diffuser",
    "product_id": null,
    "author_name": "Vihaan Singh",
    "author_initials": "VS",
    "author_location": "Pune, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Smells amazing",
    "content": "Beautiful piece. Quiet operation, even mist, and a really elegant finish. Bina soche le lo.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-22T03:00:00Z"
  },
  {
    "id": "seed-003",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "rave-scent-diffuser",
    "product_id": null,
    "author_name": "Shaurya Malhotra",
    "author_initials": "SM",
    "author_location": "Gurgaon, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Premium feel",
    "content": "Aesthetic aur functional dono. The Rave Scent Diffuser looks luxurious and the scent fills the room within minutes. A1 quality.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-19T20:00:00Z"
  },
  {
    "id": "seed-004",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "bolt-scent-diffuser",
    "product_id": null,
    "author_name": "Diya Khanna",
    "author_initials": "DK",
    "author_location": "Hyderabad, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Calming aroma",
    "content": "Loved it! The Bolt Scent Diffuser turns my whole room into a spa. Build quality is top-notch and packaging was premium.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-20T13:00:00Z"
  },
  {
    "id": "seed-005",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "rave-scent-diffuser",
    "product_id": null,
    "author_name": "Yash Chawla",
    "author_initials": "YC",
    "author_location": "Chennai, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "So elegant",
    "content": "The Rave Scent Diffuser is gorgeous and the mist is so fine and even. Pura ghar mehkta rehta hai. Premium build, totally worth it.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-19T06:00:00Z"
  },
  {
    "id": "seed-006",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "noire-scent-diffuser",
    "product_id": null,
    "author_name": "Shaurya Malhotra",
    "author_initials": "SM",
    "author_location": "Chennai, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Smells amazing",
    "content": "Best diffuser I've owned. Whisper quiet, beautiful light, and the scent throw is amazing. Macha diya!",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-16T23:00:00Z"
  },
  {
    "id": "seed-007",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "bolt-scent-diffuser",
    "product_id": null,
    "author_name": "Kabir Khanna",
    "author_initials": "KK",
    "author_location": "Surat, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "So elegant",
    "content": "The Bolt Scent Diffuser is gorgeous and the mist is so fine and even. Pura ghar mehkta rehta hai. Premium build, totally worth it.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-17T16:00:00Z"
  },
  {
    "id": "seed-008",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "rave-scent-diffuser",
    "product_id": null,
    "author_name": "Nikita Bose",
    "author_initials": "NB",
    "author_location": "Indore, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 4,
    "title": "Really good",
    "content": "Good value. Calming fragrance and quiet operation. Would've loved one more light mode but still a solid buy.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-16T09:00:00Z"
  },
  {
    "id": "seed-009",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "core-scent-diffuser",
    "product_id": null,
    "author_name": "Riya Kapoor",
    "author_initials": "RK",
    "author_location": "Lucknow, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Smells amazing",
    "content": "Loved it! The Core Scent Diffuser turns my whole room into a spa. Build quality is top-notch and packaging was premium.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-14T02:00:00Z"
  },
  {
    "id": "seed-010",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "cavix",
    "product_id": null,
    "author_name": "Kabir Khanna",
    "author_initials": "KK",
    "author_location": "Kolkata, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Premium feel",
    "content": "The Cavix Scent Diffuser exceeded my expectations. Premium material, gentle mist, and the scent stays for long. Chha gaye!",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-14T19:00:00Z"
  },
  {
    "id": "seed-011",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "noire-scent-diffuser",
    "product_id": null,
    "author_name": "Aditya Rao",
    "author_initials": "AR",
    "author_location": "Delhi, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Calming aroma",
    "content": "Kamaal ka product. The aroma is calming and the design is so classy. Mehmaan bhi poochte hain. Highly recommend.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-12T12:00:00Z"
  },
  {
    "id": "seed-012",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "cavix",
    "product_id": null,
    "author_name": "Navya Reddy",
    "author_initials": "NR",
    "author_location": "Noida, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 3,
    "title": "Pleasant but subtle",
    "content": "Decent diffuser. The scent is pleasant but the mist felt a bit light for a large room. Okay for the price.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-11T05:00:00Z"
  },
  {
    "id": "seed-013",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "noire-scent-diffuser",
    "product_id": null,
    "author_name": "Kavya Iyer",
    "author_initials": "KI",
    "author_location": "Chennai, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Top-notch quality",
    "content": "Beautiful piece. Quiet operation, even mist, and a really elegant finish. Bina soche le lo.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-11T22:00:00Z"
  },
  {
    "id": "seed-014",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "titan-scent-diffuser",
    "product_id": null,
    "author_name": "Kabir Khanna",
    "author_initials": "KK",
    "author_location": "Gurgaon, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 4,
    "title": "Happy with it",
    "content": "Great aroma and premium look. Mist is nice and fine. Runtime could be slightly longer but happy overall.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-09T15:00:00Z"
  },
  {
    "id": "seed-015",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "titan-scent-diffuser",
    "product_id": null,
    "author_name": "Jahnvi Joshi",
    "author_initials": "JJ",
    "author_location": "Chandigarh, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 4,
    "title": "Great scent",
    "content": "Good value. Calming fragrance and quiet operation. Would've loved one more light mode but still a solid buy.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-08T08:00:00Z"
  },
  {
    "id": "seed-016",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "bolt-scent-diffuser",
    "product_id": null,
    "author_name": "Sneha Desai",
    "author_initials": "SD",
    "author_location": "Kolkata, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 4,
    "title": "Classy & quiet",
    "content": "Nice product, fills the room well and the Bolt Scent Diffuser looks classy. Took a couple of extra days to arrive but worth it.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-09T01:00:00Z"
  },
  {
    "id": "seed-017",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "core-scent-diffuser",
    "product_id": null,
    "author_name": "Ritika Sen",
    "author_initials": "RS",
    "author_location": "Hyderabad, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Top-notch quality",
    "content": "Kamaal ka product. The aroma is calming and the design is so classy. Mehmaan bhi poochte hain. Highly recommend.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-06T18:00:00Z"
  },
  {
    "id": "seed-018",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "core-scent-diffuser",
    "product_id": null,
    "author_name": "Ritika Sen",
    "author_initials": "RS",
    "author_location": "Kolkata, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Worth every rupee",
    "content": "Obsessed with my Core Scent Diffuser! The fragrance lasts for hours and it looks so elegant on the table. Bohot premium feel hai.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-04T11:00:00Z"
  },
  {
    "id": "seed-019",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "titan-scent-diffuser",
    "product_id": null,
    "author_name": "Karan Bhatia",
    "author_initials": "KB",
    "author_location": "Jaipur, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "So elegant",
    "content": "My living room smells like a 5-star hotel now. Titan Scent Diffuser ki quality ekdum premium hai. Fast delivery too.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-06T04:00:00Z"
  },
  {
    "id": "seed-020",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "core-scent-diffuser",
    "product_id": null,
    "author_name": "Ritika Sen",
    "author_initials": "RS",
    "author_location": "Lucknow, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Love it",
    "content": "Super happy with this. Sturdy build, soothing light modes, and a consistent fragrance. Jhakaas!",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-03T21:00:00Z"
  },
  {
    "id": "seed-021",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "core-scent-diffuser",
    "product_id": null,
    "author_name": "Aman Sharma",
    "author_initials": "AS",
    "author_location": "Chennai, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Obsessed!",
    "content": "Beautiful piece. Quiet operation, even mist, and a really elegant finish. Bina soche le lo.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-01T14:00:00Z"
  },
  {
    "id": "seed-022",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "cavix",
    "product_id": null,
    "author_name": "Rishabh Desai",
    "author_initials": "RD",
    "author_location": "Gurgaon, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Worth every rupee",
    "content": "Best diffuser I've owned. Whisper quiet, beautiful light, and the scent throw is amazing. Macha diya!",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-03T07:00:00Z"
  },
  {
    "id": "seed-023",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "cavix",
    "product_id": null,
    "author_name": "Megha Reddy",
    "author_initials": "MR",
    "author_location": "Indore, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Obsessed!",
    "content": "Loved it! The Cavix Scent Diffuser turns my whole room into a spa. Build quality is top-notch and packaging was premium.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-06-01T00:00:00Z"
  },
  {
    "id": "seed-024",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "rave-scent-diffuser",
    "product_id": null,
    "author_name": "Ishaan Trivedi",
    "author_initials": "IT",
    "author_location": "Chandigarh, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Premium feel",
    "content": "Super happy with this. Sturdy build, soothing light modes, and a consistent fragrance. Jhakaas!",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-29T17:00:00Z"
  },
  {
    "id": "seed-025",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "noire-scent-diffuser",
    "product_id": null,
    "author_name": "Ananya Mehta",
    "author_initials": "AM",
    "author_location": "Kolkata, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 4,
    "title": "Good value",
    "content": "Good value. Calming fragrance and quiet operation. Would've loved one more light mode but still a solid buy.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-31T10:00:00Z"
  },
  {
    "id": "seed-026",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "cavix",
    "product_id": null,
    "author_name": "Ananya Mehta",
    "author_initials": "AM",
    "author_location": "Kolkata, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Smells amazing",
    "content": "Aesthetic aur functional dono. The Cavix Scent Diffuser looks luxurious and the scent fills the room within minutes. A1 quality.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-29T03:00:00Z"
  },
  {
    "id": "seed-027",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "bolt-scent-diffuser",
    "product_id": null,
    "author_name": "Navya Reddy",
    "author_initials": "NR",
    "author_location": "Delhi, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 4,
    "title": "Happy with it",
    "content": "Solid build and pleasant scent throw. The Bolt Scent Diffuser looks premium on my shelf. Happy with the purchase.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-26T20:00:00Z"
  },
  {
    "id": "seed-028",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "core-scent-diffuser",
    "product_id": null,
    "author_name": "Megha Reddy",
    "author_initials": "MR",
    "author_location": "Noida, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Obsessed!",
    "content": "This Core Scent Diffuser is stunning. Fine mist, long-lasting fragrance, and runs silently all night. Worth every rupee.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-27T13:00:00Z"
  },
  {
    "id": "seed-029",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "cavix",
    "product_id": null,
    "author_name": "Anjali Saxena",
    "author_initials": "AS",
    "author_location": "Chandigarh, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Calming aroma",
    "content": "The Cavix Scent Diffuser is gorgeous and the mist is so fine and even. Pura ghar mehkta rehta hai. Premium build, totally worth it.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-26T06:00:00Z"
  },
  {
    "id": "seed-030",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "cavix",
    "product_id": null,
    "author_name": "Myra Bhatia",
    "author_initials": "MB",
    "author_location": "Noida, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Smells amazing",
    "content": "Super happy with this. Sturdy build, soothing light modes, and a consistent fragrance. Jhakaas!",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-23T23:00:00Z"
  },
  {
    "id": "seed-031",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "bolt-scent-diffuser",
    "product_id": null,
    "author_name": "Rishabh Desai",
    "author_initials": "RD",
    "author_location": "Chennai, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 3,
    "title": "Pleasant but subtle",
    "content": "Decent diffuser. The scent is pleasant but the mist felt a bit light for a large room. Okay for the price.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-24T16:00:00Z"
  },
  {
    "id": "seed-032",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "noire-scent-diffuser",
    "product_id": null,
    "author_name": "Megha Reddy",
    "author_initials": "MR",
    "author_location": "Lucknow, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 4,
    "title": "Classy & quiet",
    "content": "Great aroma and premium look. Mist is nice and fine. Runtime could be slightly longer but happy overall.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-23T09:00:00Z"
  },
  {
    "id": "seed-033",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "noire-scent-diffuser",
    "product_id": null,
    "author_name": "Jahnvi Joshi",
    "author_initials": "JJ",
    "author_location": "Pune, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Smells amazing",
    "content": "Genuinely impressed. Looks high-end, runs silent, and one fill lasts ages. Perfect for the bedroom.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-21T02:00:00Z"
  },
  {
    "id": "seed-034",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "bolt-scent-diffuser",
    "product_id": null,
    "author_name": "Vihaan Singh",
    "author_initials": "VS",
    "author_location": "Gurgaon, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 4,
    "title": "Really good",
    "content": "Good value. Calming fragrance and quiet operation. Would've loved one more light mode but still a solid buy.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-21T19:00:00Z"
  },
  {
    "id": "seed-035",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "rave-scent-diffuser",
    "product_id": null,
    "author_name": "Ishaan Trivedi",
    "author_initials": "IT",
    "author_location": "Bengaluru, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Love it",
    "content": "This Rave Scent Diffuser is stunning. Fine mist, long-lasting fragrance, and runs silently all night. Worth every rupee.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-19T12:00:00Z"
  },
  {
    "id": "seed-036",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "core-scent-diffuser",
    "product_id": null,
    "author_name": "Rohan Malhotra",
    "author_initials": "RM",
    "author_location": "Gurgaon, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 3,
    "title": "Pleasant but subtle",
    "content": "Decent diffuser. The scent is pleasant but the mist felt a bit light for a large room. Okay for the price.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-18T05:00:00Z"
  },
  {
    "id": "seed-037",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "bolt-scent-diffuser",
    "product_id": null,
    "author_name": "Ananya Mehta",
    "author_initials": "AM",
    "author_location": "Surat, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Premium feel",
    "content": "My living room smells like a 5-star hotel now. Bolt Scent Diffuser ki quality ekdum premium hai. Fast delivery too.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-18T22:00:00Z"
  },
  {
    "id": "seed-038",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "noire-scent-diffuser",
    "product_id": null,
    "author_name": "Neil DSouza",
    "author_initials": "ND",
    "author_location": "Surat, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 4,
    "title": "Happy with it",
    "content": "Nice product, fills the room well and the Noirè Scent Diffuser looks classy. Took a couple of extra days to arrive but worth it.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-16T15:00:00Z"
  },
  {
    "id": "seed-039",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "titan-scent-diffuser",
    "product_id": null,
    "author_name": "Pooja Verma",
    "author_initials": "PV",
    "author_location": "Pune, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "So elegant",
    "content": "Loved it! The Titan Scent Diffuser turns my whole room into a spa. Build quality is top-notch and packaging was premium.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-15T08:00:00Z"
  },
  {
    "id": "seed-040",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "rave-scent-diffuser",
    "product_id": null,
    "author_name": "Rohan Malhotra",
    "author_initials": "RM",
    "author_location": "Chandigarh, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Calming aroma",
    "content": "Obsessed with my Rave Scent Diffuser! The fragrance lasts for hours and it looks so elegant on the table. Bohot premium feel hai.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-16T01:00:00Z"
  },
  {
    "id": "seed-041",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "titan-scent-diffuser",
    "product_id": null,
    "author_name": "Siddharth Roy",
    "author_initials": "SR",
    "author_location": "Bengaluru, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Love it",
    "content": "Beautiful piece. Quiet operation, even mist, and a really elegant finish. Bina soche le lo.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-13T18:00:00Z"
  },
  {
    "id": "seed-042",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "rave-scent-diffuser",
    "product_id": null,
    "author_name": "Myra Bhatia",
    "author_initials": "MB",
    "author_location": "Lucknow, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Top-notch quality",
    "content": "Kamaal ka product. The aroma is calming and the design is so classy. Mehmaan bhi poochte hain. Highly recommend.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-11T11:00:00Z"
  },
  {
    "id": "seed-043",
    "shop_domain": "jifhga-rm.myshopify.com",
    "product_handle": "titan-scent-diffuser",
    "product_id": null,
    "author_name": "Anjali Saxena",
    "author_initials": "AS",
    "author_location": "Bengaluru, India",
    "is_verified": true,
    "is_featured": false,
    "rating": 5,
    "title": "Top-notch quality",
    "content": "This Titan Scent Diffuser is stunning. Fine mist, long-lasting fragrance, and runs silently all night. Worth every rupee.",
    "image_urls": [],
    "video_url": null,
    "reply": null,
    "reply_at": null,
    "created_at": "2026-05-13T04:00:00Z"
  }
];
